version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - LOG_LEVEL=INFO
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
